server:
  port: 3344

spring:
  application:
    name: microservice-config  #该微服务的名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/paopaodog/SpringCloudConfig.git   #配置文件所在的 github 仓库地址
#          uri: git@github.com:paopaodog/SpringCloudConfig.git   #配置文件所在的 github 仓库地址
          username: paopaodog
          password: springcloud8080

